import Head from 'next/head';
import { Inter } from '@next/font/google';
import Carousel from '@/components/Carousel';
import * as React from 'react';
import { styled } from '@mui/material/styles';
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';


export default function Home() {
  return (
    <Box >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>    
      <Grid container rowSpacing={{ xs: 1, sm: 2, md: 3 }} columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
       <Grid item xs={12} sm={6} md={4} lg={3} xl={4}>    
         <Carousel/>
      </Grid>
       <Grid item xs={12} sm={6} md={4} lg={3} xl={4}>    
        <Carousel/>
      </Grid>
       <Grid item xs={12} sm={6} md={4} lg={3} xl={4}>    
         <Carousel/>
      </Grid>
       <Grid item xs={12} sm={6} md={4} lg={3} xl={4}>    
        <Carousel/>
      </Grid>
     </Grid>
    </Box>
  )
}

/*
xs, extra-small: 0px
sm, small: 600px
md, medium: 900px
lg, large: 1200px
xl, extra-large: 1536px
*/
