import Head from 'next/head';
import {images,juiceImgs,disposableImg,accessoryImg} from '@/utils/images';
import dynamic from 'next/dynamic';
import Carousel from '@/components/Carousel';
import * as React from 'react';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import styles from '@/styles/Home.module.css';
const HeroSection = dynamic(() =>import( '@/components/HeroSection'),{ssr: false});
/**DRAWER STUFF */
import logo from '../public/logo.png';
import { useStoreContext } from '@/utils/GlobalState';
import { TOGGLE_DRAWER } from '@/utils/actions';
import { styled, useTheme } from "@mui/material/styles";
import Drawer from "@mui/material/Drawer";
import List from "@mui/material/List";
import Divider from "@mui/material/Divider";
import IconButton from "@mui/material/IconButton";
import ChevronLeftIcon from "@mui/icons-material/ChevronLeft";
import ChevronRightIcon from "@mui/icons-material/ChevronRight";
import ListItem from "@mui/material/ListItem";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import InboxIcon from "@mui/icons-material/MoveToInbox";
import MailIcon from "@mui/icons-material/Mail";
import InfoIcon from '@mui/icons-material/Info';

const drawerWidth = 240;

const DrawerHeader = styled("div")(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  padding: theme.spacing(0, 1),
  // necessary for content to be below app bar
  ...theme.mixins.toolbar,
  justifyContent: "flex-start",
 
}));
/**DRAWER STUFF */


const boxStyle = {
  padding:{xs:'1rem',md:'3%'},
  width:{md:'100%'}
};

export default function Home() {
  /**DRAWER STUFF */
  const theme = useTheme();
  //const [open, setOpen] = React.useState(false);
  const [state,dispatch] = useStoreContext();



  const handleDrawerClose = () => {
    dispatch({type:TOGGLE_DRAWER});
  };
  /**DRAWER STUFF */
  return (
    <>
     <Head>
        <title>Vape Avenue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head> 

    

      <HeroSection/>
    <Box sx={boxStyle}>   
      <Grid container rowSpacing={{ xs: 3, sm: 2, md: 3 }} columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
       <Grid item xs={12} sm={6} lg={3} > 
       <section className={styles.productSection}>
        <h1 className={styles.productSecH1}>Mods</h1>
         <Carousel images={images}/>
        </section>   
      </Grid>
       <Grid item xs={12} sm={6}  lg={3}>    
         <section className={styles.productSection}>
        <h1 className={styles.productSecH1}>Juice</h1>
         <Carousel images={juiceImgs}/>
        </section>
      </Grid>
       <Grid item xs={12} sm={6}  lg={3}>    
         <section className={styles.productSection}>
        <h1 className={styles.productSecH1}>Disposable</h1>
         <Carousel images={disposableImg}/>
        </section>
      </Grid>
       <Grid item xs={12} sm={6} lg={3}>    
         <section className={styles.productSection}>
        <h1 className={styles.productSecH1}>Accessories</h1>
         <Carousel images={accessoryImg}/>
        </section>
      </Grid>
     </Grid>
    </Box>
     {/*drawer code***********************************************************************/}
    <Box sx={{ display: "flex",backgroundColor:'rgb(214, 219, 220)' }}>
     

      <Drawer
        sx={{
          width: drawerWidth,
          flexShrink: 0,
          "& .MuiDrawer-paper": {
            width: drawerWidth
          },
        }}
        variant="persistent"
        anchor="right"
        open={state.drawerOpen}
      >
        <DrawerHeader>
          <IconButton onClick={handleDrawerClose}>
            {theme.direction === "rtl" ? (
              <ChevronLeftIcon />
            ) : (
              <ChevronRightIcon sx={{color:'#5FAEBF'}}/>
            )}
          </IconButton>
        </DrawerHeader>
        <Divider/>
        <List>
          {["About us","Contact Us"].map((text, index) => (
            <ListItem key={text} disablePadding>
              <ListItemButton>
                <ListItemIcon>
                  {index % 2 === 0 ? <InfoIcon sx={{color:'#5FAEBF'}}/> : <MailIcon sx={{color:'#5FAEBF'}}/>}
                </ListItemIcon>
                <ListItemText sx={{color:'#5FAEBF'}} primary={text} />
              </ListItemButton>
            </ListItem>
          ))}
        </List>
      
          <img
          className={styles.regImg}
           src='/logo.png'
           alt='vape avenue logo'
          width='100%'
          />
          <div className={styles.brandDiv}>
          <img
          className={styles.regImg}
           src='/frutia-brand.png'
           alt='vape avenue logo'
          width='100%'
          />
          <img
          className={styles.regImg}
           src='/ruthless-brand.png'
           alt='vape avenue logo'
          width='100%'
          />
          <img
          className={styles.regImg}
           src='/twist-brand.png'
           alt='vape avenue logo'
          width='100%'
          />
          <img
          className={styles.regImg}
           src='/milk-brand.png'
           alt='vape avenue logo'
          width='100%'
          />
       </div>
      </Drawer>
    </Box>
    </>
  )
}

/*
xs, extra-small: 0px
sm, small: 600px
md, medium: 900px
lg, large: 1200px
xl, extra-large: 1536px
*/
